services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dormduty-backend
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env.dev
    volumes:
      - ./api:/app
      - ./logs:/var/log/api
    restart: always

  db:
    image: postgres:17
    container_name: dormduty-pg
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: dormduty
      POSTGRES_PASSWORD: password
      pgdata: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  pgdata:
