name: Build & Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r api/requirements.txt

      - name: Zip the app
        run: |
          cd api
          zip -r ../app.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-app
          path: app.zip

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fastapi-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: dormduty-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
